### ISSUE TITLE
How can I find the main.py file?

### ISSUE THREAD

**Issue by lzq8272587** [jasmeet0915/S.T.A.R#1]
Hi:

Many thanks for your awesome work!

After downloading the project, I did not find the main.py file which is introduced in the README.md. Did I miss something? How can I run this demo?

Thanks!

Best,

**Comment by jasmeet0915** [comment]
Hi, thank you for pointing that out!
That was a mistake in the README.md. The name of the file is not main.py it is 2BodyProblem.py.
I have updated the readme with the change.

This is the main script which reads the TLE data, propagates the satellite and then overwrites the blender particle cache with satellite position data. After the script overwrites the cache data, you can open the earth.blend1 file in blender and it should animate the particles with the satellite position data from the particle cache.
